#服务端口
server:
  port: 10000
spring:
#  服务名
  application:
    name: canal-client
#  环境设置：dev（development 开发）、test（测试）、prod（product 正式）
  profiles:
    active: dev
#数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 19970508
